CREATE TABLE IF NOT EXISTS programs (
    id VARCHAR(36) PRIMARY KEY,
    university_id VARCHAR(36) NOT NULL,
    program_name VARCHAR(500) NOT NULL,
    degree_type ENUM('bachelor', 'master_coursework', 'master_research', 'phd') NOT NULL,
    field VARCHAR(200) NOT NULL,
    field_category VARCHAR(100) NULL,
    description TEXT NULL,
    requirements JSON NULL,
    deadline DATE NULL,
    tuition_usd DECIMAL(10, 2) NULL,
    duration_years DECIMAL(3, 1) NULL,
    ranking_score DECIMAL(5, 2) NULL,
    source_url VARCHAR(500) NOT NULL,
    crawled_at TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (university_id) REFERENCES universities(id) ON DELETE CASCADE,
    INDEX idx_field (field),
    INDEX idx_degree_type (degree_type),
    INDEX idx_deadline (deadline),
    INDEX idx_crawled_at (crawled_at),
    INDEX idx_university_field (university_id, field),
    FULLTEXT INDEX ft_program_name_description (program_name, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
